### PR TITLE
Features, small refactors, documentation

### PR DESCRIPTION
**Pull request by jayserdny**
Changes made:

- Middleware to check if a user is banned and prevent further actions
- Modification of the schema for posts and users to add more fields
- Function to ban users (only for supervisors)
- Make the posts endpoint "universal" (so, v1/posts/ will return all posts, v1/posts?author=jaysermendez will return only posts by me, v1/posts?category=music will return posts only from music, v1/posts?search=music will search for posts with the keyword music or related). All the fields can be combined in the URL.
- Indexation of author and category in post schema
- API Documentation for posts endpoint, "ban" endpoint
- Add master user the first time the server run
- Remove user object from user schema since it is redundant (data can change and we don't want this fixed data)
- Prevent moderators to moderate a post more than once
- Middleware to check if a post is moderated. If so, prevent any moderator to moderate it again
- Merge all moderation tools into a single endpoint for more consistency
- Refactor of single post endpoint to follow project guidelines and linter
- Add "isVoted" field for posts endpoint so you can know if you have voted any of the posts returned
- API documentation for single post endpoint
- Change group name for moderation tools in the API docs
- Validation of fields for "ban" endpoint
- Validation for moderate endpoint

### CODE REVIEW

**Review by the-codingninja — APPROVED** [review]

**Comment by the-codingninja** [comment]
Great Work Buddy! :slightly_smiling_face: 

You smell like Microsoft

**Comment by jayserdny** [comment]
Will see if I smell like it next week :D

**Comment by onozasi** [comment]
fragrant

**Comment by jayserdny** [comment]
Traced

**Pull request merged**
